// <auto-generated />
namespace Iteedee.BetaDepot.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class TeamMembershop_Repo_Nav : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamMembershop_Repo_Nav));
        
        string IMigrationMetadata.Id
        {
            get { return "201404071900181_TeamMembershop_Repo_Nav"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
