// <auto-generated />
namespace Iteedee.BetaDepot.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class ReceiveBuildNotifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReceiveBuildNotifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201404161900023_ReceiveBuildNotifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
