// <auto-generated />
namespace Iteedee.BetaDepot.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Added_IsSystemUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_IsSystemUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201403211433546_Added_IsSystemUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
